name: Compile CMake Project

on: [push, pull_request]

env:
  CXX: g++
  CC: gcc

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ pip
        sudo pip install conan
        
    - name: Install CMake
      run: |
        CMAKE_VERSION=3.18.4
        CMAKE_DIR=cmake-${CMAKE_VERSION}-Linux-x86_64
        CMAKE_TAR=${CMAKE_DIR}.tar.gz
        wget https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/${CMAKE_TAR}
        tar xf ${CMAKE_TAR}
        export PATH=$PWD/${CMAKE_DIR}/bin:$PATH
        cmake --version
        
    - name: Install libusb
      run: sudo apt install -y libusb-1.0-0-dev libudev-dev

    - name: Compile project
      run: |
        mkdir build
        cd build
        conan install .. --build=missing  -c tools.system.package_manager:mode=install -c tools.system.package_manager:sudo=True
        cmake ..
        cmake --build .

