name: Compile CMake Project

on: [push, pull_request]

env:
  CXX: g++
  CC: gcc

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ pip
        sudo pip install conan
        
    - name: Install latest CMake
      run: |
        sudo apt-get update --fix-missing && sudo apt upgrade -y
        sudo apt-get install software-properties-common
        sudo add-apt-repository --yes ppa:kitware/cmake
        sudo apt-get update
        sudo apt-get install -y cmake
        
    - name: Install libudev
      run: |
        sudo apt-get update && sudo apt upgrade -y
        sudo apt-get install -y libudev-dev


    - name: Compile project
      run: |
        mkdir build
        cd build
        conan install .. --build=missing  -c tools.system.package_manager:mode=install -c tools.system.package_manager:sudo=True
        cmake ..
        cmake --build .

